FROM Ubuntu
RUN mkdir /opt/tomcat/

WORKDIR /opt/tomcat

RUN yum -y install java
RUN java -version

RUN curl -O https://downloads.apache.org/tomcat/tomcat-10/v10.1.8/bin/apache-tomcat-10.1.8.tar.gz
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat-10.1.8/* /opt/tomcat/.

WORKDIR /opt/tomcat/webapps
RUN curl -O -L https://github.com/Thavamanin12/Hello-world-Maven/tree/master/dist/Hello-world-app-1.0.0.war

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]

